/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppTimelineRouteImport } from './routes/_app.timeline'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppResolutionRouteImport } from './routes/_app.resolution'
import { Route as AppReportRouteImport } from './routes/_app.report'
import { Route as AppProfileRouteImport } from './routes/_app.profile'
import { Route as AppIngestRouteImport } from './routes/_app.ingest'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppClustersRouteImport } from './routes/_app.clusters'
import { Route as AppAiCommandCenterRouteImport } from './routes/_app.ai-command-center'

const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTimelineRoute = AppTimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppResolutionRoute = AppResolutionRouteImport.update({
  id: '/resolution',
  path: '/resolution',
  getParentRoute: () => AppRoute,
} as any)
const AppReportRoute = AppReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppIngestRoute = AppIngestRouteImport.update({
  id: '/ingest',
  path: '/ingest',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppClustersRoute = AppClustersRouteImport.update({
  id: '/clusters',
  path: '/clusters',
  getParentRoute: () => AppRoute,
} as any)
const AppAiCommandCenterRoute = AppAiCommandCenterRouteImport.update({
  id: '/ai-command-center',
  path: '/ai-command-center',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/sign-up': typeof SignUpRoute
  '/signin': typeof SigninRoute
  '/ai-command-center': typeof AppAiCommandCenterRoute
  '/clusters': typeof AppClustersRoute
  '/dashboard': typeof AppDashboardRoute
  '/ingest': typeof AppIngestRoute
  '/profile': typeof AppProfileRoute
  '/report': typeof AppReportRoute
  '/resolution': typeof AppResolutionRoute
  '/settings': typeof AppSettingsRoute
  '/timeline': typeof AppTimelineRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/sign-up': typeof SignUpRoute
  '/signin': typeof SigninRoute
  '/ai-command-center': typeof AppAiCommandCenterRoute
  '/clusters': typeof AppClustersRoute
  '/dashboard': typeof AppDashboardRoute
  '/ingest': typeof AppIngestRoute
  '/profile': typeof AppProfileRoute
  '/report': typeof AppReportRoute
  '/resolution': typeof AppResolutionRoute
  '/settings': typeof AppSettingsRoute
  '/timeline': typeof AppTimelineRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/sign-up': typeof SignUpRoute
  '/signin': typeof SigninRoute
  '/_app/ai-command-center': typeof AppAiCommandCenterRoute
  '/_app/clusters': typeof AppClustersRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/ingest': typeof AppIngestRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/report': typeof AppReportRoute
  '/_app/resolution': typeof AppResolutionRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/timeline': typeof AppTimelineRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/sign-up'
    | '/signin'
    | '/ai-command-center'
    | '/clusters'
    | '/dashboard'
    | '/ingest'
    | '/profile'
    | '/report'
    | '/resolution'
    | '/settings'
    | '/timeline'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/sign-up'
    | '/signin'
    | '/ai-command-center'
    | '/clusters'
    | '/dashboard'
    | '/ingest'
    | '/profile'
    | '/report'
    | '/resolution'
    | '/settings'
    | '/timeline'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/forgot-password'
    | '/sign-up'
    | '/signin'
    | '/_app/ai-command-center'
    | '/_app/clusters'
    | '/_app/dashboard'
    | '/_app/ingest'
    | '/_app/profile'
    | '/_app/report'
    | '/_app/resolution'
    | '/_app/settings'
    | '/_app/timeline'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  SignUpRoute: typeof SignUpRoute
  SigninRoute: typeof SigninRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/timeline': {
      id: '/_app/timeline'
      path: '/timeline'
      fullPath: '/timeline'
      preLoaderRoute: typeof AppTimelineRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/resolution': {
      id: '/_app/resolution'
      path: '/resolution'
      fullPath: '/resolution'
      preLoaderRoute: typeof AppResolutionRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/report': {
      id: '/_app/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof AppReportRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ingest': {
      id: '/_app/ingest'
      path: '/ingest'
      fullPath: '/ingest'
      preLoaderRoute: typeof AppIngestRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/clusters': {
      id: '/_app/clusters'
      path: '/clusters'
      fullPath: '/clusters'
      preLoaderRoute: typeof AppClustersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ai-command-center': {
      id: '/_app/ai-command-center'
      path: '/ai-command-center'
      fullPath: '/ai-command-center'
      preLoaderRoute: typeof AppAiCommandCenterRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAiCommandCenterRoute: typeof AppAiCommandCenterRoute
  AppClustersRoute: typeof AppClustersRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppIngestRoute: typeof AppIngestRoute
  AppProfileRoute: typeof AppProfileRoute
  AppReportRoute: typeof AppReportRoute
  AppResolutionRoute: typeof AppResolutionRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppTimelineRoute: typeof AppTimelineRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAiCommandCenterRoute: AppAiCommandCenterRoute,
  AppClustersRoute: AppClustersRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppIngestRoute: AppIngestRoute,
  AppProfileRoute: AppProfileRoute,
  AppReportRoute: AppReportRoute,
  AppResolutionRoute: AppResolutionRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppTimelineRoute: AppTimelineRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  SignUpRoute: SignUpRoute,
  SigninRoute: SigninRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
